# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sharvik World
email: sharvik@sharvik.world
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 5

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/david00medina
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/david-alberto-medina-medina-523a85188/
pinterest_url:
slack_url:
twitter_url: https://x.com/SharvikWorld
youtube_url: https://www.youtube.com/@SharvikWorld
twitch_url: https://www.twitch.tv/sharvik_

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jektex
  - jekyll-archives

# Archives
collections:
  sections:
    output: true
    permalink: /section/:path/
    order:
      - cybersecurity-sanctuary.md
      - ai-wonderland.md
      - codecraft-corner.md
      - math-marvels.md
      - robotics-and-electronics-oasis.md
      - genome-forge.md


# Jekyll archives
jekyll-archives:
  enabled:
    - categories
    - year
  layouts:
    year: archive-year
    category: archive-category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


# Page listing order
page_order:
  - Home
  - Categories
  - Archive
  - Donate
  - Contact
  - About

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
